library(ggplot2)
svm_cl = read.csv('csv/svm_cl.csv', header=FALSE)
names(svm_cl) = c('Team', 'Predicted', 'Actual')
svm_pr = read.csv('csv/svm_pr.csv', header=FALSE)
names(svm_pr) = c('Team', 'Predicted', 'Actual', 'Color')
rf_cl = read.csv('csv/random_forest.csv', header=FALSE)
names(rf_cl) = c('Team', 'Predicted', 'Actual')
rf_pr = read.csv('csv/random_forest_prob.csv', header=FALSE)
names(rf_pr) = c('Team', 'Predicted', 'Actual')
c <- as.character(svm_pr$Color)
t <- as.character(svm_pr$Team)
ggplot(svm_cl, aes(Predicted, Actual, label=Team, fill=Team, color=Team, group=1)) + geom_abline(slope=1, color='gray',group=2) + geom_point() + geom_text(nudge_y=1) + coord_cartesian(xlim=c(0,82), ylim=c(0,82)) + scale_fill_manual(values=as.character(colors)) + scale_color_manual(values=c[order(t)])+ theme(legend.position="none") + ggtitle('SVM Binary Classification')
ggplot(rf_cl, aes(Predicted, Actual, label=Team, fill=Team, color=Team, group=1)) + geom_abline(slope=1, color='gray',group=2) + geom_point() + geom_text(nudge_y=1) + coord_cartesian(xlim=c(0,82), ylim=c(0,82)) + scale_fill_manual(values=as.character(colors)) + scale_color_manual(values=c[order(t)])+ theme(legend.position="none") + ggtitle('Random Forest Binary Classification')
ggplot(svm_pr, aes(Predicted, Actual, label=Team, fill=Team, color=Team, group=1)) + geom_abline(slope=1, color='gray',group=2) + geom_point() + geom_text(nudge_y=1) + coord_cartesian(xlim=c(0,82), ylim=c(0,82)) + scale_fill_manual(values=as.character(colors)) + scale_color_manual(values=c[order(t)])+ theme(legend.position="none") + ggtitle('SVM Probability Classification')
ggplot(rf_pr, aes(Predicted, Actual, label=Team, fill=Team, color=Team, group=1)) + geom_abline(slope=1, color='gray',group=2) + geom_point() + geom_text(nudge_y=1) + coord_cartesian(xlim=c(0,82), ylim=c(0,82)) + scale_fill_manual(values=as.character(colors)) + scale_color_manual(values=c[order(t)])+ theme(legend.position="none") + ggtitle('Random Forest Probability Classification')